[env]
_.file = '.env'

[tools]
node = "lts"
python = "latest"
uv = "latest"
"npm:git-cz" = "latest"
"npm:mcp-hub" = "latest"
"npm:vercel" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:wrangler" = "latest"
"npm:mmcp" = "latest"
"npm:tsx" = "latest"
"npm:dotenv-cli" = "latest"
rust = "latest"
pnpm = "latest"
go = "latest"
yarn = "latest"

[settings]
experimental = true
